### PR TITLE
gRPC-API: service definitions for Gateway, Clouds and Geese services.

### PR DESCRIPTION
**Pull request by alxbnet**
Added API definitions for API Gateway, Geese and Clouds services.

### CODE REVIEW

**Comment by HalloGene** [comment]
@mykyta-protsenko I agree to stick with getting entire level at once. 
I don't think sending one request per line is a good approach.
How difficult is it to implement streaming of geese and clouds?

**Comment by alxbnet** [comment]
@HalloGene @mykyta-protsenko getting an entire level would eliminate the need of streaming. It also means client receives unnecessary data upfront. What if a player doesn't reach the end of a level? Why client needs entire level fixture?
If line-by-line is too much, we can do by screen (or by X lines, which is effectively the same).

**Comment by mykyta-protsenko** [comment]
@alxbnet @HalloGene Would it? You can still stream levels using flow-control, right? (just let the client decide when to get a next level - or screen. Screen looks fine to me.)

**Comment by mykyta-protsenko** [comment]
Actually, I just got an idea how to bring together streaming and upfront fetching. Let's convert request to something like `streamBatches(int n)` - a client can request to start a stream of batches, where each batch will have `n` lines.

@alxbnet @HalloGene your thoughts?

**Comment by HalloGene** [comment]
I'm not sure if we need levels at all. We can apply this approach: game starts and difficulty gradually increases (frequency of geese and/or speed goes up) until the player eventually loses.

Regarding streaming: We have to decide who controls the flow. I'd prefer it to be backend and the frontend know just a little piece of info in advance or know nothing. Backend decides when to send a new portion of geese (some interval not necessary constant or any other logic).

I like suggested format streamBatches(int n). It's looking good to me now.

**Pull request merged**
